import React, { createContext, useContext, useState, useCallback, useMemo, useEffect, ReactNode } from 'react';

export type Language = 'vi' | 'en' | 'ko' | 'ja' | 'zh' | 'de';

interface Translations {
  [key: string]: any; // Allow nested objects or string access
}

const translations: Record<Language, Translations> = {
  vi: {
    nav: {
      home: 'Trang chủ',
      about: 'Giới thiệu',
      solutions: 'Giải pháp',
      products: 'Sản phẩm',
      projects: 'Dự án',
      news: 'Tin tức',
      resources: 'Tài liệu',
      contact: 'Liên hệ',
      // Submenus
      'GIẢI PHÁP TOÀN DIỆN': 'Giải pháp toàn diện',
      'HỆ THỐNG NĂNG LƯỢNG MẶT TRỜI TRÊN MÁI NHÀ': 'Điện mặt trời áp mái',
      'TRANG TRẠI NĂNG LƯỢNG MẶT TRỜI': 'Trang trại điện mặt trời',
      'HỆ THỐNG NĂNG LƯỢNG MẶT TRỜI NỔI': 'Điện mặt trời nổi',
      'TẤM PIN NĂNG LƯỢNG MẶT TRỜI': 'Tấm pin năng lượng',
      'BỘ HÒA LƯỚI (INVERTER)': 'Bộ hòa lưới (Inverter)',
      'HỆ THỐNG LƯU TRỮ ĐIỆN': 'Hệ thống lưu trữ',
      'PHỤ KIỆN LẮP ĐẶT': 'Phụ kiện lắp đặt'
    },
    header: {
      slogan: 'Giải pháp EPC và Năng lượng tái tạo hàng đầu Việt Nam',
      admin: 'Quản trị',
      hotline: 'Hotline'
    },
    footer: {
      about_title: 'Về chúng tôi',
      quick_links: 'Liên kết nhanh',
      solutions_title: 'Giải pháp',
      contact_title: 'Liên hệ',
      desc: 'Công ty Cổ phần Xây lắp Bưu điện Miền Trung (CTC). Doanh nghiệp hàng đầu trong lĩnh vực xây lắp và năng lượng tái tạo.',
      address: '50B Nguyễn Du, Phường Thạch Thang, Quận Hải Châu, TP Đà Nẵng',
      copyright: '© 2026 CTC. Bảo lưu mọi quyền.'
    },
    common: {
      loading: 'Đang tải...',
      search: 'Tìm kiếm...',
      light: 'Sáng',
      dark: 'Tối',
      theme_light: 'Chế độ sáng',
      theme_dark: 'Chế độ tối',
      theme_auto: 'Theo hệ thống',
      view_details: 'Chi tiết',
      add_to_cart: 'Thêm vào giỏ',
      buy_now: 'Mua ngay',
      close: 'Đóng',
      cancel: 'Hủy',
      save: 'Lưu',
      delete: 'Xóa',
      edit: 'Sửa',
      add: 'Thêm',
      action: 'Hành động',
      image: 'Hình ảnh',
      name: 'Tên',
      category: 'Danh mục',
      price: 'Giá',
      stock: 'Kho',
      description: 'Mô tả',
      status: 'Trạng thái',
      in_stock: 'Còn hàng',
      out_of_stock: 'Hết hàng',
      all_categories: 'Tất cả danh mục',
      all: 'Tất cả'
    },
    home: {
      hero_badge: 'Hơn 32 năm phát triển vững mạnh',
      hero_title: 'Giải pháp EPC',
      hero_subtitle: 'Hàng đầu Việt Nam',
      hero_desc: 'CTC mang đến giải pháp xây lắp và năng lượng tái tạo toàn diện, kiến tạo hạ tầng kỹ thuật bền vững.',
      get_quote: 'Nhận báo giá',
      view_projects: 'Xem dự án',
      why_choose: 'Tại sao chọn chúng tôi',
      why_choose_title: 'Giải pháp năng lượng chuẩn quốc tế',
      why_choose_desc: 'Chúng tôi không chỉ lắp đặt thiết bị, chúng tôi mang đến giải pháp đầu tư tài chính bền vững và an toàn tuyệt đối cho ngôi nhà của bạn.',
      latest_products: 'Sản phẩm mới',
      latest_products_desc: 'Chúng tôi chỉ phân phối các dòng thiết bị Top 5 thế giới (Tier 1) để đảm bảo độ bền và hiệu suất.',
      view_all_products: 'Xem tất cả',
      projects_badge: 'Dự án',
      featured_projects: 'Dự án tiêu biểu',
      featured_projects_sub: 'Những công trình khẳng định chất lượng và uy tín của CTC.',
      testimonials: 'Đánh giá khách hàng',
      testimonials_title: 'Khách hàng nói gì về chúng tôi',
      news_events: 'Tin tức & Sự kiện',
      news_badge: 'Tin tức',
      read_more: 'Đọc tiếp',
      cta_badge: 'Bắt đầu ngay',
      cta_title_1: 'Sẵn sàng chuyển đổi',
      cta_title_2: 'sang năng lượng xanh?',
      call_now: 'Gọi ngay',
      free_consult: 'Tư vấn miễn phí',
      warranty_25: 'Bảo hành 25 năm',
      save_70: 'Hiệu quả đầu tư',
      ready_to_switch: 'Sẵn sàng hợp tác cùng CTC?',
      ready_desc: 'Liên hệ với CTC ngay hôm nay để được khảo sát và tư vấn miễn phí giải pháp tối ưu nhất cho dự án của bạn.',
      contact_consult: 'Liên hệ tư vấn',
      partners_title: 'Đối tác công nghệ hàng đầu',
      partners_supplier: 'ĐỐI TÁC CUNG CẤP',
      partners_financial: 'ĐỐI TÁC TÀI CHÍNH',
      
      // Stats
      stat_assets: 'Tổng tài sản',
      stat_partners: 'Đối tác chiến lược',
      stat_capacity: 'Tổng công suất',
      stat_satisfaction: 'Kỹ sư chủ chốt',

      // Workflow
      workflow_badge: 'Quy trình',
      workflow_title: 'Quy trình triển khai tiêu chuẩn',
      step_1: 'Khảo sát & Tư vấn',
      step_1_desc: 'Đánh giá hiện trạng mái và nhu cầu sử dụng điện.',
      step_2: 'Thiết kế kỹ thuật',
      step_2_desc: 'Lên bản vẽ chi tiết và mô phỏng sản lượng điện.',
      step_3: 'Thi công lắp đặt',
      step_3_desc: 'Lắp đặt nhanh chóng, an toàn, đúng tiêu chuẩn.',
      step_4: 'Bảo hành & O&M',
      step_4_desc: 'Giám sát hệ thống 24/7 và bảo trì định kỳ.',

      // Why items
      why_1_title: "Hiệu suất tối đa", 
      why_1_desc: "Cam kết hiệu suất hệ thống đạt trên 80% nhờ thiết kế tối ưu và thiết bị cao cấp Tier 1.",
      why_2_title: "Bảo hành 25 năm", 
      why_2_desc: "Chính sách bảo hành 1 đổi 1 cho tấm pin trong 12 năm, bảo hành hiệu suất 25 năm.",
      why_3_title: "Kỹ thuật chuyên sâu", 
      why_3_desc: "Đội ngũ kỹ sư được đào tạo bài bản, có chứng chỉ hành nghề và kinh nghiệm thực chiến.",
      why_4_title: "Lưu trữ thông minh", 
      why_4_desc: "Hệ thống Hybrid/ESS giúp bạn tự chủ nguồn điện 24/7, không lo mất điện lưới.",
      why_5_title: "Thương hiệu uy tín", 
      why_5_desc: "Đối tác chiến lược của Huawei, Canadian Solar, Longi tại thị trường Việt Nam.",
      why_6_title: "Cam kết xanh", 
      why_6_desc: "Mỗi hệ thống lắp đặt giúp giảm hàng tấn CO2, tương đương trồng hàng trăm cây xanh.",

      // FAQ
      support_badge: 'Hỗ trợ',
      faq_title: 'Câu hỏi thường gặp',
      faq_desc: 'Giải đáp những thắc mắc phổ biến của khách hàng về dịch vụ EPC, viễn thông và năng lượng tái tạo của CTC.',
      need_help: 'Cần hỗ trợ thêm?',
      contact_advisor: 'Liên hệ tư vấn viên',
      faq_1_q: "CTC cung cấp những dịch vụ EPC nào?",
      faq_1_a: "CTC cung cấp dịch vụ EPC (Engineering – Procurement – Construction) trọn gói cho các lĩnh vực:\n• Hạ tầng viễn thông (Trạm BTS, tuyến cáp quang, mạng OSP ngoại vi)\n• CNTT & Data Center (Hệ thống máy chủ, lưu trữ, giám sát thông minh)\n• Năng lượng tái tạo (Điện mặt trời mái nhà C&I, Solar Farm, Điện gió)\n• Hạ tầng kỹ thuật, đường dây và trạm biến áp đến 110kV\nChúng tôi đảm nhận trọn gói từ khảo sát, thiết kế, cung ứng thiết bị đến thi công và O&M.",
      faq_2_q: "CTC có kinh nghiệm thi công các dự án quy mô lớn không?",
      faq_2_a: "Có. CTC đã triển khai thành công hơn 500 dự án trong hơn 32 năm phát triển, tiêu biểu gồm:\n• Nhà máy điện gió Hướng Linh 1 & 2, Hướng Hiệp 1\n• Các dự án trạm BTS viễn thông lớn cho Mobifone, Vinaphone trên toàn quốc\n• Hệ thống cáp quang truyền dẫn cho VNPT và Bộ Công an\n• Các dự án điện mặt trời áp mái nhà xưởng quy mô 2-5MWp cho đối tác FDI",
      faq_3_q: "CTC có chứng chỉ năng lực xây dựng không?",
      faq_3_a: "Có. CTC được Bộ Xây dựng cấp Chứng chỉ năng lực hoạt động xây dựng với thứ hạng cao cho các lĩnh vực:\n• Thi công xây dựng công trình Hạ tầng kỹ thuật, Công nghiệp, Dân dụng\n• Thiết kế và giám sát thi công đường dây & trạm biến áp đến 110kV\n• Lắp đặt thiết bị chuyên biệt hệ thống Viễn thông, Điện tử & Công nghệ thông tin\nĐây là bảo chứng vững chắc cho chất lượng kỹ thuật của chúng tôi.",
      faq_4_q: "Quy trình ký hợp đồng và triển khai dự án với CTC như thế nào?",
      faq_4_a: "Quy trình triển khai 5 bước tiêu chuẩn quốc tế:\n1. Tiếp nhận thông tin & khảo sát thực địa miễn phí trong 24 giờ.\n2. Lập phương án thiết kế kỹ thuật tối ưu & dự toán ngân sách chi tiết.\n3. Thương thảo và tiến hành ký kết hợp đồng EPC trọn gói.\n4. Tổ chức thi công chuyên nghiệp, đảm bảo an toàn, chất lượng & tiến độ.\n5. Nghiệm thu bàn giao đưa vào vận hành, hỗ trợ thủ tục đấu nối & O&M định kỳ.\nLiên hệ Hotline 0915.059.666 để bắt đầu khảo sát ngay!",
      
      // About Company
      about_badge: 'VỀ CHÚNG TÔI',
      about_title: 'CTC - Đối tác tin cậy của bạn',
      about_desc: 'Công ty Cổ phần Xây lắp Bưu điện Miền Trung (CTC) tự hào với hơn 32 năm phát triển, là đơn vị chuyên cung cấp giải pháp tổng thể theo mô hình EPC (Engineering – Procurement – Construction) và Design & Build.',
      about_desc_2: 'Chúng tôi đảm nhận toàn bộ quy trình từ khảo sát, tư vấn, thiết kế, thi công đến vận hành bảo trì, giúp tối ưu chi phí và đảm bảo tính đồng bộ của dự án.',
      mission: 'Sứ mệnh',
      mission_desc: 'Giải pháp kỹ thuật toàn diện',
      vision: 'Tầm nhìn',
      vision_desc: 'Doanh nghiệp hàng đầu Việt Nam',
      values: 'Giá trị',
      values_desc: 'Uy tín - Chất lượng - An toàn',
      learn_more: 'Tìm hiểu thêm',
      contact_us: 'Liên hệ ngay',
      
      // Team
      team_badge: 'ĐỘI NGŨ CHUYÊN NGHIỆP',
      team_title: 'Gặp gỡ đội ngũ chuyên gia của chúng tôi',
      team_desc: 'Đội ngũ kỹ sư và chuyên gia giàu kinh nghiệm, tận tâm mang đến giải pháp tối ưu nhất cho khách hàng.',
      team_ceo: 'Giám đốc điều hành',
      team_cto: 'Giám đốc công nghệ',
      team_engineer: 'Kỹ sư trưởng',
      team_manager: 'Quản lý dự án',
      join_team: 'Gia nhập đội ngũ của chúng tôi',
      join_team_title: 'Cùng kiến tạo',
      join_team_highlight: 'Tương lai xanh',
      opportunity: 'Cơ hội',
      join_team_desc: 'Chúng tôi luôn tìm kiếm những tài năng xuất sắc để cùng phát triển và kiến tạo tương lai năng lượng xanh.',
      apply_now: 'Ứng tuyển ngay'
    },
    admin: {
      dashboard: 'Tổng quan',
      users: 'Quản Lý Tài Khoản',
      content: 'Quản lý nội dung',
      products: 'Sản phẩm',
      projects: 'Dự án',
      news: 'Tin tức',
      testimonials: 'Khách hàng',
      partners: 'Đối tác',
      settings: 'Cấu hình',
      categories: 'Quản Lý Danh Mục',
      reviews: 'Đánh Giá Khách Hàng',
      goals: 'Quản lý Mục tiêu',
      contacts: 'Quản Lý Liên Hệ',
      team: 'Quản Lý Nhân Viên',
      project_categories: 'DM Dự án',
      news_categories: 'DM Tin tức',
      document_categories: 'Thể loại tài liệu',
      logout: 'Thoát',
      welcome: 'Xin chào',
      search_placeholder: 'Tìm kiếm trong admin...',
      manage_content: 'Quản lý nội dung',
      // Settings
      settings_title: 'Cấu hình hệ thống',
      general_info: 'Thông tin chung',
      site_name: 'Tên Website',
      maintenance_mode: 'Chế độ bảo trì',
      contact_info: 'Thông tin liên hệ',
      security: 'Bảo mật & Thông báo',
      save_success: 'Lưu cấu hình thành công!'
    },
    contact: {
      title: 'Liên hệ với chúng tôi',
      desc: 'Để lại thông tin để được tư vấn miễn phí',
      company_info: 'Thông tin công ty',
      form_title: 'Gửi yêu cầu tư vấn',
      name: 'Họ và tên',
      phone: 'Số điện thoại',
      email: 'Email',
      service: 'Dịch vụ quan tâm',
      message: 'Nội dung',
      submit: 'Gửi yêu cầu',
      success: 'Gửi thành công!'
    },
    about: {
      hero_badge: 'Hơn 32 Năm Phát Triển',
      hero_title: 'CTC',
      hero_subtitle: '"Tổng thầu thiết kế, cung cấp thiết bị và thi công (EPC) hàng đầu Việt Nam"',
      ceo_title: 'Ông Nguyễn Văn Duy',
      ceo_role: 'Tổng Giám Đốc',
      milestone_1: 'Thành lập',
      milestone_1_desc: 'Khởi nguồn từ đơn vị xây lắp thuộc ngành Bưu chính – Viễn thông Việt Nam.',
      milestone_2: 'Mở rộng đa ngành',
      milestone_2_desc: 'Triển khai hàng trăm công trình viễn thông, năng lượng tái tạo, công nghiệp, dân dụng.',
      letter_title: 'Tổng quan Công ty',
      letter_greeting: '"Công ty Cổ phần Xây lắp Bưu điện Miền Trung (CTC) tự hào là đối tác tin cậy của nhiều tập đoàn lớn."',
      letter_p1: 'Khởi nguồn từ đơn vị xây lắp thuộc ngành Bưu chính – Viễn thông Việt Nam, CTC đã không ngừng đổi mới, mở rộng lĩnh vực hoạt động và đầu tư vào nguồn nhân lực, công nghệ cũng như hệ thống quản lý chất lượng.',
      letter_p2: 'Đến nay, công ty đã trở thành đối tác tin cậy của nhiều tập đoàn viễn thông, doanh nghiệp năng lượng, cơ quan nhà nước và các chủ đầu tư trong và ngoài nước. CTC cung cấp giải pháp tổng thể theo mô hình EPC và Design & Build.',
      core_val_title: 'Giá trị cốt lõi',
      core_val_desc: 'Uy tín - Chất lượng - An toàn - Hiệu quả - Đổi mới - Hợp tác - Trách nhiệm',
      vision_title: 'Tầm nhìn & Sứ mệnh',
      vision_subtitle: 'Hướng tới trở thành doanh nghiệp hàng đầu Việt Nam trong lĩnh vực xây lắp và năng lượng tái tạo.',
      mission: 'Sứ mệnh',
      mission_desc: 'Cam kết mang đến cho khách hàng các giải pháp kỹ thuật toàn diện, từ tư vấn, thiết kế đến thi công và vận hành, với chất lượng cao, tiến độ đảm bảo và chi phí tối ưu.',
      vision: 'Tầm nhìn',
      vision_desc: 'Trở thành doanh nghiệp hàng đầu Việt Nam trong lĩnh vực xây lắp hạ tầng viễn thông, năng lượng tái tạo và hạ tầng kỹ thuật; đồng thời là đơn vị tiên phong cung cấp các giải pháp tích hợp.',
      core_trust: 'Uy tín',
      core_quality: 'Chất lượng',
      core_portfolio: 'Danh mục đầu tư',
      areas_title: 'Hoạt Động Kinh Doanh',
      // Areas of Operation
      area_epc: 'Tổng thầu EPC',
      area_epc_desc: 'Thiết kế, Cung cấp thiết bị & Thi công trọn gói các dự án điện mặt trời áp mái và mặt đất.',
      area_design: 'Tư vấn & Thiết kế',
      area_design_desc: 'Lập dự án đầu tư, thiết kế kỹ thuật, thẩm tra thiết kế và dự toán công trình điện.',
      area_dist: 'Phân phối thiết bị',
      area_dist_desc: 'Đại lý chính hãng các thương hiệu Pin (Canadian, Longi) và Inverter (Huawei, SMA).',
      area_invest: 'Đầu tư năng lượng',
      area_invest_desc: 'Xây dựng kế hoạch và trực tiếp đầu tư các dự án năng lượng dài hạn.'
    },
    solutions: {
      hero_title: 'Giải Pháp Năng Lượng',
      hero_subtitle: 'Toàn Diện & Bền Vững',
      hero_desc: 'Tối ưu hóa chi phí, bảo vệ môi trường và kiến tạo tương lai xanh với các mô hình điện mặt trời hiện đại nhất từ CTC.',
      category_title: 'Danh mục giải pháp',
      rooftop: 'Điện mặt trời Áp mái',
      rooftop_desc: 'Tận dụng không gian mái nhà xưởng, văn phòng hoặc hộ gia đình để tạo ra điện năng. Giải pháp tiết kiệm chi phí hiệu quả nhất.',
      farm: 'Trang trại Điện mặt trời',
      farm_desc: 'Các dự án quy mô lớn, kết nối lưới điện quốc gia. Đóng góp quan trọng vào an ninh năng lượng và phát triển kinh tế.',
      floating: 'Điện mặt trời Nổi',
      floating_desc: 'Công nghệ tiên tiến lắp đặt trên mặt nước (hồ chứa, đập thủy điện). Tăng hiệu suất và bảo vệ tài nguyên đất.',
      cta_title: 'Bạn chưa biết giải pháp nào phù hợp?',
      cta_desc: 'Hãy để đội ngũ kỹ sư của chúng tôi khảo sát và tư vấn miễn phí dựa trên nhu cầu thực tế của bạn.',
      cta_btn: 'Liên hệ tư vấn ngay',
      discover: 'Khám phá',
      // Sidebar
      other_services: 'Dịch vụ khác',
      smart_invest: 'Đầu tư thông minh',
      invest_desc: 'Hoàn vốn chỉ sau 4-5 năm. Hưởng lợi ích miễn phí lên đến 20 năm tiếp theo.',
      get_advice: 'Nhận tư vấn ngay'
    },
    products: {
        filter: 'Bộ lọc',
        filter_tech: 'Thông số kỹ thuật',
        power: 'Công suất (W)',
        efficiency: 'Hiệu suất (%)',
        min: 'Tối thiểu',
        max: 'Tối đa',
        sort: 'Sắp xếp',
        sort_default: 'Mặc định',
        sort_price_asc: 'Giá: Thấp đến Cao',
        sort_price_desc: 'Giá: Cao đến Thấp',
        sort_name_asc: 'Tên: A-Z',
        category_list: 'Danh mục sản phẩm',
        tech_support: 'Cần tư vấn kỹ thuật?',
        tech_support_desc: 'Đội ngũ kỹ sư của chúng tôi sẵn sàng hỗ trợ chọn thiết bị phù hợp.',
        contact_now: 'Liên hệ ngay',
        search_placeholder: 'Tìm kiếm tên sản phẩm, mã...',
        no_result: 'Không tìm thấy sản phẩm nào',
        no_result_desc: 'Vui lòng thử lại với từ khóa hoặc danh mục khác.',
        clear_filter: 'Xóa bộ lọc',
        found: 'Tìm thấy',
        products: 'sản phẩm',
        eff_basic: 'Cơ bản < 90%',
        eff_good: 'Tốt 90-95%',
        eff_high: 'Cao > 95%',
        eff_optimal: 'Tối ưu > 98%',
        // Detail Page
        detail_tab_desc: 'Chi tiết sản phẩm',
        detail_tab_specs: 'Thông số kỹ thuật',
        detail_tab_reviews: 'Đánh giá',
        call_to_buy: 'Liên hệ mua hàng',
        add_to_quote: 'Thêm vào báo giá',
        share: 'Chia sẻ sản phẩm này',
        warranty: 'Bảo hành',
        authentic: 'Chính hãng',
        payment: 'Thanh toán',
        years: 'Năm',
        write_review: 'Viết đánh giá',
        no_reviews: 'Chưa có đánh giá nào cho sản phẩm này.',
        be_first: 'Hãy là người đầu tiên chia sẻ trải nghiệm của bạn!',
        market_price: 'Giá thị trường',
        contact_price: 'Liên hệ báo giá',
        reviews: 'đánh giá',
        views: 'lượt xem',
        product_price: 'Giá sản phẩm',
        like: 'Thích',
        share_btn: 'Chia sẻ',
        ai_analyzing: 'AI đang phân tích...',
        ai_click: 'Click để dùng AI CTC',
        ai_summary_desc: 'Tóm tắt thông số kỹ thuật',
        ai_summary: 'AI Tóm tắt',
        ai_comparing: 'AI đang so sánh...',
        ai_compare_desc: 'So sánh với sản phẩm khác',
        ai_compare: 'AI So sánh',
        key_features: 'Tính năng nổi bật',
        tech_details: 'Chi tiết kỹ thuật',
        related_products: 'Sản phẩm liên quan'
    },
    projects: {
        title: 'Dự án đã triển khai',
        subtitle: 'Hành trình kiến tạo năng lượng xanh trên khắp Việt Nam.',
        capacity: 'Công suất',
        location: 'Địa điểm',
        completion: 'Hoàn thành',
        type: 'Loại hình',
        status: 'Trạng thái',
        view_detail: 'Xem chi tiết',
        no_projects: 'Hiện chưa có dự án nào.'
    },
    news: {
        title: 'Tin tức & Sự kiện',
        subtitle: 'Cập nhật tin tức mới nhất về công nghệ điện mặt trời, xu hướng năng lượng tái tạo và hoạt động của CTC.',
        no_news: 'Hiện chưa có tin tức nào.'
    },
    resources: {
      title: 'Thư viện Tài liệu & Hỗ trợ',
      subtitle: 'Truy cập catalogue, hướng dẫn sử dụng và chính sách.',
      catalogue: 'Catalogue',
      manual: 'Hướng dẫn sử dụng',
      policy: 'Chính sách bảo hành',
      download: 'Tải xuống'
    },
    calculator: {
      title: 'Công cụ tính toán',
      bill_label: 'Hóa đơn tiền điện trung bình tháng',
      disclaimer: '*Kết quả chỉ mang tính chất tham khảo.',
      system_size: 'Hệ thống đề xuất',
      monthly_savings: 'Tiết kiệm hàng tháng',
      investment: 'Chi phí đầu tư (Ước tính)',
      roi: 'Thời gian hoàn vốn',
      years: 'Năm',
      consult_btn: 'Tư vấn lắp đặt gói này',
      intro_badge: 'Công cụ miễn phí',
      intro_title: 'Dự toán chi phí & Lợi nhuận đầu tư',
      intro_desc: 'Bạn muốn lắp đặt điện mặt trời nhưng chưa biết chi phí bao nhiêu? Sử dụng công cụ tính toán nhanh của chúng tôi để có cái nhìn tổng quan nhất về hệ thống phù hợp với hóa đơn tiền điện của bạn.',
      feature_1_title: 'Chính xác đến 95%',
      feature_1_desc: 'Dựa trên dữ liệu bức xạ thực tế tại Việt Nam.',
      feature_2_title: 'Cập nhật giá thị trường',
      feature_2_desc: 'Đơn giá thiết bị được cập nhật hàng tuần.',
      usage_type: 'Loại hình sử dụng điện',
      household: 'Hộ gia đình',
      household_desc: 'Điện sinh hoạt',
      company: 'Công ty',
      company_desc: 'Điện kinh doanh',
      daytime_usage: 'Tỷ lệ dùng điện ban ngày',
      all_night: 'Tất cả ban đêm',
      all_day: 'Tất cả ban ngày',
      tip: 'Gợi ý',
      tip_residential: 'Hộ gia đình thường dùng 20-40% điện ban ngày (nấu ăn, giặt giũ, điều hòa buổi trưa).',
      tip_commercial: 'Công ty/Văn phòng thường dùng 70-90% điện ban ngày (giờ làm việc 8h-17h).',
      system_capacity: 'CÔNG SUẤT HỆ THỐNG NÊN LẮP',
      storage: 'LƯU TRỮ (nếu có)',
      estimated_bill: 'TIỀN ĐIỆN DỰ KIẾN',
      max_savings: 'SỐ TIỀN TIẾT KIỆM TỐI ĐA',
      recommended_area: 'DIỆN TÍCH KHUYẾN NGHỊ',
      per_month: '/tháng'
    },
    chat: {
      support: 'Hỗ trợ trực tuyến',
      reply_time: 'Thường trả lời trong vài phút',
      welcome: 'Trợ lý AI CTC xin kính chào quý khách. Quý khách cần hỗ trợ thông tin gì?',
      placeholder: 'Nhập tin nhắn...',
      typing: 'Đang nhập...',
      send: 'Gửi'
    },
    login: {
      title: 'Đăng nhập Quản trị',
      email: 'Email',
      password: 'Mật khẩu',
      btn: 'Đăng nhập',
      error: 'Email hoặc mật khẩu không đúng',
      weak_password: 'Mật khẩu phải có ít nhất 6 ký tự',
      back: 'Quay lại trang chủ'
    }
  },
  en: {
    nav: {
      home: 'Home',
      about: 'About Us',
      solutions: 'Solutions',
      products: 'Products',
      projects: 'Projects',
      news: 'News',
      resources: 'Resources',
      contact: 'Contact',
      // Submenus
      'GIẢI PHÁP TOÀN DIỆN': 'Comprehensive Solutions',
      'HỆ THỐNG NĂNG LƯỢNG MẶT TRỜI TRÊN MÁI NHÀ': 'Rooftop Solar',
      'TRANG TRẠI NĂNG LƯỢNG MẶT TRỜI': 'Solar Farm',
      'HỆ THỐNG NĂNG LƯỢNG MẶT TRỜI NỔI': 'Floating Solar',
      'TẤM PIN NĂNG LƯỢNG MẶT TRỜI': 'Solar Panels',
      'BỘ HÒA LƯỚI (INVERTER)': 'Inverters',
      'HỆ THỐNG LƯU TRỮ ĐIỆN': 'Energy Storage',
      'PHỤ KIỆN LẮP ĐẶT': 'Mounting & Accessories'
    },
    header: {
      slogan: 'Leading Solar Energy Solutions in Vietnam',
      admin: 'Admin',
      hotline: 'Hotline'
    },
    footer: {
      about_title: 'About Us',
      quick_links: 'Quick Links',
      solutions_title: 'Solutions',
      contact_title: 'Contact Info',
      desc: 'Central Vietnam Posts and Telecommunications Construction Joint Stock Company (CTC). Pioneering in renewable energy.',
      address: '50B Nguyen Du, Hai Chau, Da Nang',
      copyright: '© 2026 CTC. All rights reserved.'
    },
    common: {
      loading: 'Loading...',
      search: 'Search...',
      light: 'Light',
      dark: 'Dark',
      theme_light: 'Light Mode',
      theme_dark: 'Dark Mode',
      theme_auto: 'System Default',
      view_details: 'Details',
      add_to_cart: 'Add to Cart',
      buy_now: 'Buy Now',
      close: 'Close',
      cancel: 'Cancel',
      save: 'Save',
      delete: 'Delete',
      edit: 'Edit',
      add: 'Add',
      action: 'Action',
      image: 'Image',
      name: 'Name',
      category: 'Category',
      price: 'Price',
      stock: 'Stock',
      description: 'Description',
      status: 'Status',
      in_stock: 'In Stock',
      out_of_stock: 'Out of Stock',
      all_categories: 'All Categories',
      all: 'All'
    },
    home: {
      hero_badge: 'Latest AI Inverter Technology 2026',
      hero_title: 'Clean Energy',
      hero_subtitle: 'Sustainable Investment',
      hero_desc: 'CTC provides comprehensive solar solutions, helping you save costs and build a green future.',
      get_quote: 'Get Quote',
      view_projects: 'View Projects',
      why_choose: 'Why Choose Us',
      why_choose_title: 'International Standard Energy Solutions',
      why_choose_desc: 'We don\'t just install equipment, we provide sustainable financial investment solutions and absolute safety for your home.',
      latest_products: 'Latest Products',
      latest_products_desc: 'We only distribute Top 5 global devices (Tier 1) to ensure durability and efficiency.',
      view_all_products: 'View All',
      projects_badge: 'Projects',
      featured_projects: 'Featured Projects',
      featured_projects_sub: 'Projects that affirm the quality of CTC.',
      testimonials: 'Customer Reviews',
      testimonials_title: 'What Our Customers Say',
      news_events: 'News & Events',
      news_badge: 'News',
      read_more: 'Read More',
      cta_badge: 'Get Started',
      cta_title_1: 'Ready to switch',
      cta_title_2: 'to green energy?',
      call_now: 'Call Now',
      free_consult: 'Free Consultation',
      warranty_25: '25 Years Warranty',
      save_70: 'Save 70% on Energy',
      ready_to_switch: 'Ready to switch to green energy?',
      ready_desc: 'Contact CTC today for a free survey and consultation on the most optimal solution for your home. Save 70% on your electricity bill immediately.',
      contact_consult: 'Contact Us',
      partners_title: 'Leading Technology Partners',
      partners_supplier: 'SUPPLIER PARTNERS',
      partners_financial: 'FINANCIAL PARTNERS',

      // Stats
      stat_assets: 'Total Assets',
      stat_partners: 'Strategic Partners',
      stat_capacity: 'Total Capacity',
      stat_satisfaction: 'Key Engineers',

       // Workflow
      workflow_badge: 'Process',
      workflow_title: 'Standard Implementation Process',
      step_1: 'Survey & Consult',
      step_1_desc: 'Evaluate roof condition and electricity demand.',
      step_2: 'Technical Design',
      step_2_desc: 'Detailed drawings and yield simulation.',
      step_3: 'Installation',
      step_3_desc: 'Fast, safe, and standard installation.',
      step_4: 'Warranty & O&M',
      step_4_desc: '24/7 monitoring and periodic maintenance.',

       // Why items
      why_1_title: "Max Performance", 
      why_1_desc: "Commitment to system performance over 80% thanks to optimal design and Tier 1 equipment.",
      why_2_title: "25-Year Warranty", 
      why_2_desc: "1-for-1 exchange policy for panels in 12 years, performance warranty of 25 years.",
      why_3_title: "Expert Engineering", 
      why_3_desc: "Engineers are well-trained, certified, and have practical experience.",
      why_4_title: "Smart Storage", 
      why_4_desc: "Hybrid/ESS systems help you master your power source 24/7, no worries about grid outages.",
      why_5_title: "Reputable Brands", 
      why_5_desc: "Strategic partner of Huawei, Canadian Solar, Longi in the Vietnam market.",
      why_6_title: "Green Commitment", 
      why_6_desc: "Each installed system helps reduce tons of CO2, equivalent to planting hundreds of trees.",

      // FAQ
      support_badge: 'Support',
      faq_title: 'Frequently Asked Questions',
      faq_desc: 'Answers to common questions about CTC EPC services, telecom infrastructure, and renewable energy.',
      need_help: 'Need more help?',
      contact_advisor: 'Contact an Advisor',
      faq_1_q: "What EPC services does CTC provide?",
      faq_1_a: "CTC offers turnkey EPC (Engineering – Procurement – Construction) services in:\n• Telecom infrastructure (BTS stations, fiber optic networks, external OSP network)\n• IT & Data Center systems (servers, storage, smart surveillance)\n• Renewable energy (industrial rooftop solar, solar farms, wind power)\n• Technical infrastructure, power grid transmission up to 110kV\nWe manage the full lifecycle from surveying and design to deployment and O&M.",
      faq_2_q: "Does CTC have experience with large-scale projects?",
      faq_2_a: "Yes. CTC has completed over 500 large-scale projects during 32+ years of operation, including:\n• Huong Linh 1 & 2, Huong Hiep 1 wind power plants\n• Nationwide telecom BTS station networks for major telcos (Mobifone, Vinaphone)\n• Core backbone fiber transmission for VNPT and Ministry of Public Security\n• Rooftop solar projects for multi-MWp scale factories.",
      faq_3_q: "Does CTC hold construction capability certificates?",
      faq_3_a: "Yes. CTC is certified by the Ministry of Construction for key capabilities:\n• Construction of Technical Infrastructure, Industrial, and Civil works\n• Engineering design & construction inspection of power lines & substations up to 110kV\n• Installation of specialized telecom, electronics & IT technology equipment\nThis represents a gold guarantee for CTC's quality standards.",
      faq_4_q: "What is the project signing and execution process with CTC?",
      faq_4_a: "We follow a standardized 5-step process:\n1. Receive customer request & perform free on-site survey within 24 hours.\n2. Develop optimal engineering design & detailed cost estimation.\n3. Negotiate terms and execute the complete turnkey EPC contract.\n4. Mobilize resources, construct safely with strict quality control.\n5. Commissioning, handover, support utility grid connection & periodic O&M.\nCall Hotline 0915.059.666 to start your survey today!",
      
      // About Company
      about_badge: 'ABOUT US',
      about_title: 'CTC - Your Trusted Partner',
      about_desc: 'CTC Consulting and Construction Joint Stock Company (CTC) was established in 32, specializing in comprehensive renewable energy solutions with experienced engineers and advanced technology.',
      about_desc_2: 'We are proud to be a strategic partner of world-leading brands such as Huawei, Canadian Solar, Longi, bringing customers high-quality products at the most competitive prices.',
      mission: 'Mission',
      mission_desc: 'Bringing clean energy to every home',
      vision: 'Vision',
      vision_desc: 'Leading the renewable energy market',
      values: 'Values',
      values_desc: 'Trust - Quality - Sustainability',
      learn_more: 'Learn More',
      contact_us: 'Contact Now',
      
      // Team
      team_badge: 'PROFESSIONAL TEAM',
      team_title: 'Meet our team of experts',
      team_desc: 'Experienced engineers and experts, dedicated to bringing the best solutions to customers.',
      team_ceo: 'Chief Executive Officer',
      team_cto: 'Chief Technology Officer',
      team_engineer: 'Chief Engineer',
      team_manager: 'Project Manager',
      join_team: 'Join Our Team',
      join_team_title: 'Create Together',
      join_team_highlight: 'A Green Future',
      opportunity: 'Opportunity',
      join_team_desc: 'We are always looking for outstanding talents to develop together and create a green energy future.',
      apply_now: 'Apply Now'
    },
    admin: {
      dashboard: 'Dashboard',
      users: 'Account Management',
      content: 'Content Management',
      products: 'Products',
      projects: 'Projects',
      news: 'News',
      testimonials: 'Customers',
      partners: 'Partners',
      settings: 'Settings',
      categories: 'Category Management',
      reviews: 'Customer Reviews',
      goals: 'Goals Management',
      contacts: 'Contact Management',
      team: 'Staff Management',
      project_categories: 'Project Categories',
      news_categories: 'News Categories',
      document_categories: 'Document Categories',
      logout: 'Logout',
      welcome: 'Welcome',
      search_placeholder: 'Search in admin...',
      manage_content: 'Manage Content',
      // Settings
      settings_title: 'System Settings',
      general_info: 'General Information',
      site_name: 'Website Name',
      maintenance_mode: 'Maintenance Mode',
      contact_info: 'Contact Information',
      security: 'Security & Notifications',
      save_success: 'Settings saved successfully!'
    },
    contact: {
      title: 'Contact Us',
      desc: 'Leave your info for free consultation',
      company_info: 'Company Info',
      form_title: 'Send Request',
      name: 'Full Name',
      phone: 'Phone Number',
      email: 'Email',
      service: 'Service of Interest',
      message: 'Message',
      submit: 'Send Request',
      success: 'Sent Successfully!'
    },
    about: {
      hero_badge: '10 Years Pioneering',
      hero_title: 'CTC',
      hero_subtitle: '"Creating sustainable value from renewable energy, accompanying the prosperous development of customers."',
      ceo_title: 'Mr. Tran Thanh Xuan',
      ceo_role: 'General Director',
      milestone_1: 'Founded CTC',
      milestone_1_desc: 'Marking the birth of a reputable brand in the electricity industry.',
      milestone_2: 'Development Strategy',
      milestone_2_desc: 'Proactively implementing according to the National Energy Development Plan.',
      letter_title: 'CEO Letter',
      letter_greeting: '"CTC Electrical Construction and Consultancy Joint Stock Company (CTC) sends our respectful greetings and wishes for health, success, and prosperity to our valued customers!"',
      letter_p1: 'CTC Electrical Construction and Consultancy Joint Stock Company was established on November 25, 2015, right when the Vietnamese Government was focusing on prioritizing renewable energy development.',
      letter_p2: 'CTC provides a wide range of products and services essential for the renewable energy industry, from services, technical support, EPC contractors, power distributors, etc.',
      core_val_title: 'Core Values',
      core_val_desc: 'Our company\'s reputation is built on the Trust and Portfolio we have built.',
      vision_title: 'Vision & Mission',
      vision_subtitle: 'Sustainable development orientation, customer-centric.',
      mission: 'Mission',
      mission_desc: 'Providing high-quality products with optimal technical solutions, creating absolute satisfaction and long-term economic benefits for customers.',
      vision: 'Vision',
      vision_desc: 'To become the leading symbol of trust in Vietnam in the renewable energy and electrical construction industry, accompanying the national Net Zero goal.',
      core_trust: 'Trust',
      core_quality: 'Quality',
      core_portfolio: 'Portfolio',
      areas_title: 'Business Areas',
      // Areas of Operation
      area_epc: 'EPC Contractor',
      area_epc_desc: 'Design, Equipment Supply & Turnkey Construction for rooftop and ground-mounted solar projects.',
      area_design: 'Consulting & Design',
      area_design_desc: 'Investment project planning, technical design, design verification and electrical construction estimation.',
      area_dist: 'Equipment Distribution',
      area_dist_desc: 'Official distributor of Solar Panels (Canadian, Longi) and Inverters (Huawei, SMA).',
      area_invest: 'Energy Investment',
      area_invest_desc: 'Planning and directly investing in long-term energy projects.'
    },
    solutions: {
      hero_title: 'Energy Solutions',
      hero_subtitle: 'Comprehensive & Sustainable',
      hero_desc: 'Optimize costs, protect the environment, and create a green future with the most modern solar models from CTC.',
      category_title: 'Solution Categories',
      rooftop: 'Rooftop Solar',
      rooftop_desc: 'Utilize roof space of factories, offices, or households to generate electricity. The most effective cost-saving solution.',
      farm: 'Solar Farm',
      farm_desc: 'Large-scale projects connected to the national grid. Contributing significantly to energy security and economic development.',
      floating: 'Floating Solar',
      floating_desc: 'Advanced technology installed on water surfaces (reservoirs, hydropower dams). Increases efficiency and conserves land resources.',
      cta_title: 'Not sure which solution fits?',
      cta_desc: 'Let our engineering team survey and provide free consultation based on your actual needs.',
      cta_btn: 'Get Consultation',
      discover: 'Discover',
      // Sidebar
      other_services: 'Other Services',
      smart_invest: 'Smart Investment',
      invest_desc: 'Payback in just 4-5 years. Enjoy free benefits for the next 20 years.',
      get_advice: 'Get Advice Now'
    },
    products: {
        filter: 'Filter',
        filter_tech: 'Technical Specs',
        power: 'Power (W)',
        efficiency: 'Efficiency (%)',
        min: 'Min',
        max: 'Max',
        sort: 'Sort',
        sort_default: 'Default',
        sort_price_asc: 'Price: Low to High',
        sort_price_desc: 'Price: High to Low',
        sort_name_asc: 'Name: A-Z',
        category_list: 'Categories',
        tech_support: 'Need Tech Support?',
        tech_support_desc: 'Our engineering team is ready to help you choose the right equipment.',
        contact_now: 'Contact Now',
        search_placeholder: 'Search product name, code...',
        no_result: 'No products found',
        no_result_desc: 'Please try again with different keywords or categories.',
        clear_filter: 'Clear Filter',
        found: 'Found',
        products: 'products',
        eff_basic: 'Basic < 90%',
        eff_good: 'Good 90-95%',
        eff_high: 'High > 95%',
        eff_optimal: 'Optimal > 98%',
        // Detail Page
        detail_tab_desc: 'Description',
        detail_tab_specs: 'Specifications',
        detail_tab_reviews: 'Reviews',
        call_to_buy: 'Call to Buy',
        add_to_quote: 'Add to Quote',
        share: 'Share this product',
        warranty: 'Warranty',
        authentic: 'Authentic',
        payment: 'Payment',
        years: 'Years',
        write_review: 'Write Review',
        no_reviews: 'No reviews yet for this product.',
        be_first: 'Be the first to share your experience!',
        market_price: 'Market Price',
        contact_price: 'Contact for price',
        reviews: 'reviews',
        views: 'views',
        product_price: 'Product Price',
        like: 'Like',
        share_btn: 'Share',
        ai_analyzing: 'AI analyzing...',
        ai_click: 'Click to use AI CTC',
        ai_summary_desc: 'Summarize specifications',
        ai_summary: 'AI Summary',
        ai_comparing: 'AI comparing...',
        ai_compare_desc: 'Compare with other products',
        ai_compare: 'AI Comparison',
        key_features: 'Key Features',
        tech_details: 'Technical Details',
        related_products: 'Related Products'
    },
    projects: {
        title: 'Completed Projects',
        subtitle: 'Creating green energy journey across Vietnam.',
        capacity: 'Capacity',
        location: 'Location',
        completion: 'Completion',
        type: 'Type',
        status: 'Status',
        view_detail: 'View Details',
        no_projects: 'No projects found.'
    },
    news: {
        title: 'News & Events',
        subtitle: 'Update the latest news on solar technology, renewable energy trends, and CTC activities.',
        no_news: 'No news found.'
    },
    resources: {
      title: 'Resources & Support',
      subtitle: 'Access catalogues, manuals, and warranty policies.',
      catalogue: 'Catalogue',
      manual: 'User Manuals',
      policy: 'Warranty Policy',
      download: 'Download'
    },
    calculator: {
      title: 'Cost Calculator',
      bill_label: 'Average Monthly Electricity Bill',
      disclaimer: '*Results are for reference only.',
      system_size: 'Recommended System',
      monthly_savings: 'Monthly Savings',
      investment: 'Estimated Investment',
      roi: 'ROI Period',
      years: 'Years',
      consult_btn: 'Consult on this package',
      intro_badge: 'Free Tool',
      intro_title: 'Cost Estimate & ROI',
      intro_desc: 'Want to install solar but don\'t know the cost? Use our quick calculator to get an overview of the system suitable for your electricity bill.',
      feature_1_title: '95% Accuracy',
      feature_1_desc: 'Based on actual radiation data in Vietnam.',
      feature_2_title: 'Market Price Update',
      feature_2_desc: 'Equipment unit prices updated weekly.',
      usage_type: 'Power Usage Type',
      household: 'Household',
      household_desc: 'Residential electricity',
      company: 'Business',
      company_desc: 'Commercial electricity',
      daytime_usage: 'Daytime Usage Ratio',
      all_night: 'All Night',
      all_day: 'All Day',
      tip: 'Tip',
      tip_residential: 'Typical households use 20-40% electricity during daytime (cooking, laundry, afternoon AC).',
      tip_commercial: 'Companies/Offices typically use 70-90% electricity during daytime (working hours 8am-5pm).',
      system_capacity: 'RECOMMENDED SYSTEM CAPACITY',
      storage: 'STORAGE (if any)',
      estimated_bill: 'ESTIMATED ELECTRICITY BILL',
      max_savings: 'MAXIMUM SAVINGS',
      recommended_area: 'RECOMMENDED AREA',
      per_month: '/month'
    },
    chat: {
      support: 'Online Support',
      reply_time: 'Usually replies in minutes',
      welcome: 'CTC AI Assistant greets you. How can I help you today?',
      placeholder: 'Type a message...',
      typing: 'Typing...',
      send: 'Send'
    },
    login: {
      title: 'Admin Login',
      email: 'Email',
      password: 'Password',
      btn: 'Sign In',
      error: 'Invalid email or password',
      weak_password: 'Password must be at least 6 characters',
      back: 'Back to Home'
    }
  },
  // Korean (한국어)
  ko: {
    nav: {
      home: '홈',
      about: '회사 소개',
      solutions: '솔루션',
      products: '제품',
      projects: '프로젝트',
      news: '뉴스',
      resources: '자료실',
      contact: '연락처',
      'GIẢI PHÁP TOÀN DIỆN': '종합 솔루션',
      'HỆ THỐNG NĂNG LƯỢNG MẶT TRỜI TRÊN MÁI NHÀ': '옥상 태양광',
      'TRANG TRẠI NĂNG LƯỢNG MẶT TRỜI': '태양광 발전소',
      'HỆ THỐNG NĂNG LƯỢNG MẶT TRỜI NỔI': '수상 태양광',
      'TẤM PIN NĂNG LƯỢNG MẶT TRỜI': '태양광 패널',
      'BỘ HÒA LƯỚI (INVERTER)': '인버터',
      'HỆ THỐNG LƯU TRỮ ĐIỆN': '에너지 저장 시스템',
      'PHỤ KIỆN LẮP ĐẶT': '설치 부속품'
    },
    header: {
      slogan: '베트남 최고의 태양 에너지 솔루션',
      admin: '관리자',
      hotline: '핫라인'
    },
    footer: {
      about_title: '회사 소개',
      quick_links: '빠른 링크',
      solutions_title: '솔루션',
      contact_title: '연락처',
      desc: 'CTC 전기 건설 및 컨설팅 주식회사(CTC). 재생 에너지 분야의 선구자.',
      address: '259 The Lu, Son Tra, Da Nang',
      copyright: '© 2026 CTC. 모든 권리 보유.'
    },
    common: {
      loading: '로딩 중...',
      search: '검색...',
      light: '밝음',
      dark: '어두움',
      theme_light: '라이트 모드',
      theme_dark: '다크 모드',
      theme_auto: '시스템 설정',
      view_details: '상세보기',
      add_to_cart: '장바구니에 추가',
      buy_now: '지금 구매',
      close: '닫기',
      cancel: '취소',
      save: '저장',
      delete: '삭제',
      edit: '수정',
      add: '추가',
      action: '작업',
      image: '이미지',
      name: '이름',
      category: '카테고리',
      price: '가격',
      stock: '재고',
      description: '설명',
      status: '상태',
      in_stock: '재고 있음',
      out_of_stock: '품절',
      all_categories: '모든 카테고리',
      all: '전체'
    },
    home: {
      hero_badge: '최신 AI 인버터 기술 32',
      hero_title: '청정 에너지',
      hero_subtitle: '지속 가능한 투자',
      hero_desc: 'CTC는 포괄적인 태양광 솔루션을 제공하여 전기 비용을 절감하고 친환경 미래를 만듭니다.',
      get_quote: '견적 받기',
      view_projects: '프로젝트 보기',
      why_choose: '선택 이유',
      why_choose_title: '국제 표준 에너지 솔루션',
      why_choose_desc: '우리는 단순히 장비를 설치하는 것이 아니라 지속 가능한 금융 투자 솔루션과 절대적인 안전을 제공합니다.',
      latest_products: '최신 제품',
      latest_products_desc: '내구성과 효율성을 보장하기 위해 세계 Top 5 장비(Tier 1)만 유통합니다.',
      view_all_products: '모두 보기',
      projects_badge: '프로젝트',
      featured_projects: '주요 프로젝트',
      featured_projects_sub: 'CTC의 품질을 입증하는 프로젝트.',
      testimonials: '고객 후기',
      testimonials_title: '고객님들의 이야기',
      news_events: '뉴스 및 이벤트',
      news_badge: '뉴스',
      read_more: '더 읽기',
      cta_badge: '지금 시작하세요',
      cta_title_1: '녹색 에너지로',
      cta_title_2: '전환할 준비가 되셨나요?',
      call_now: '지금 전화',
      free_consult: '무료 상담',
      warranty_25: '25년 보증',
      save_70: '70% 전력 절감',
      ready_to_switch: '친환경 에너지로 전환할 준비가 되셨나요?',
      ready_desc: '오늘 CTC에 연락하여 무료 조사 및 상담을 받으세요. 전기 요금을 즉시 70% 절감하세요.',
      contact_consult: '문의하기',
      partners_title: '주요 기술 파트너',
      partners_supplier: '공급 파트너',
      partners_financial: '금융 파트너',
      stat_assets: '총 자산',
      stat_partners: '전략적 파트너',
      stat_capacity: '총 용량',
      stat_satisfaction: '핵심 엔지니어',
      workflow_badge: '프로세스',
      workflow_title: '표준 구현 프로세스',
      step_1: '조사 및 상담',
      step_1_desc: '지붕 상태 및 전력 수요 평가.',
      step_2: '기술 설계',
      step_2_desc: '상세 도면 및 발전량 시뮬레이션.',
      step_3: '설치',
      step_3_desc: '빠르고 안전하며 표준적인 설치.',
      step_4: '보증 및 유지보수',
      step_4_desc: '24/7 모니터링 및 정기 유지보수.',
      why_1_title: '최대 성능',
      why_1_desc: '최적 설계와 Tier 1 장비로 80% 이상의 시스템 성능 보장.',
      why_2_title: '25년 보증',
      why_2_desc: '12년 패널 1:1 교환 정책, 25년 성능 보증.',
      why_3_title: '전문 엔지니어링',
      why_3_desc: '잘 훈련되고 인증받은 실무 경험이 있는 엔지니어.',
      why_4_title: '스마트 저장',
      why_4_desc: 'Hybrid/ESS 시스템으로 24/7 전력 자급자족, 정전 걱정 없음.',
      why_5_title: '신뢰할 수 있는 브랜드',
      why_5_desc: '베트남 시장에서 Huawei, Canadian Solar, Longi의 전략적 파트너.',
      why_6_title: '친환경 약속',
      why_6_desc: '각 설치 시스템은 수백 그루의 나무를 심는 것과 같은 톤의 CO2를 감소시킵니다.',
      support_badge: '지원',
      faq_title: '자주 묻는 질문',
      faq_desc: '태양 에너지에 대한 일반적인 질문에 답변합니다.',
      need_help: '추가 도움이 필요하신가요?',
      contact_advisor: '상담사에게 문의',
      faq_1_q: '정전 시 태양광 시스템이 작동합니까?',
      faq_1_a: '표준 계통 연계 시스템의 경우 안전을 위해 정전 시 인버터가 차단됩니다. 그러나 Hybrid 시스템(저장 장치 포함)을 사용하면 중요한 부하에 대한 전력이 여전히 있습니다.',
      faq_2_q: '태양광 패널의 수명은 얼마나 됩니까?',
      faq_2_a: '현재 Tier 1 태양광 패널의 설계 수명은 최대 30-35년입니다. CTC는 25년 동안 80% 이상의 성능을 보증합니다.',
      faq_3_q: '유지보수 비용이 높습니까?',
      faq_3_a: '태양광 시스템은 내구성이 뛰어납니다. 유지보수는 주로 정기적인 청소(3-6개월마다)이며 비용이 매우 낮습니다.',
      faq_4_q: '설치 시간은 얼마나 걸립니까?',
      faq_4_a: '가정용(3kW - 10kW)의 경우 설치는 1-2일이 소요됩니다. 산업 프로젝트는 규모에 따라 일반적으로 2-4주가 소요됩니다.',
      about_badge: '회사 소개',
      about_title: 'CTC - 신뢰할 수 있는 파트너',
      about_desc: 'CTC 전기 컨설팅 및 건설 주식회사(CTC)는 32년에 설립되어 경험 많은 엔지니어와 첨단 기술로 포괄적인 재생 에너지 솔루션을 전문으로 합니다.',
      about_desc_2: '우리는 Huawei, Canadian Solar, Longi와 같은 세계 최고 브랜드의 전략적 파트너로서 고객에게 가장 경쟁력 있는 가격으로 고품질 제품을 제공합니다.',
      mission: '미션',
      mission_desc: '모든 가정에 청정 에너지 제공',
      vision: '비전',
      vision_desc: '재생 에너지 시장 선도',
      values: '가치',
      values_desc: '신뢰 - 품질 - 지속 가능성',
      learn_more: '더 알아보기',
      contact_us: '지금 연락하기',
      team_badge: '전문 팀',
      team_title: '전문가 팀을 만나보세요',
      team_desc: '고객에게 최상의 솔루션을 제공하는 데 전념하는 경험 많은 엔지니어와 전문가.',
      team_ceo: '최고 경영자',
      team_cto: '최고 기술 책임자',
      team_engineer: '수석 엔지니어',
      team_manager: '프로젝트 관리자',
      join_team: '우리 팀에 합류하세요',
      join_team_title: '함께 만들어가요',
      join_team_highlight: '녹색 미래',
      opportunity: '기회',
      join_team_desc: '우리는 함께 발전하고 친환경 에너지 미래를 만들 뛰어난 인재를 항상 찾고 있습니다.',
      apply_now: '지금 지원하기'
    },
    admin: {
      dashboard: '대시보드',
      users: '계정 관리',
      content: '콘텐츠 관리',
      products: '제품',
      projects: '프로젝트',
      news: '뉴스',
      testimonials: '고객',
      partners: '파트너',
      settings: '설정',
      categories: '카테고리 관리',
      reviews: '고객 리뷰',
      goals: '목표 관리',
      contacts: '연락처 관리',
      team: '직원 관리',
      project_categories: '프로젝트 카테고리',
      news_categories: '뉴스 카테고리',
      logout: '로그아웃',
      welcome: '환영합니다',
      search_placeholder: '관리자에서 검색...',
      manage_content: '콘텐츠 관리',
      settings_title: '시스템 설정',
      general_info: '일반 정보',
      site_name: '웹사이트 이름',
      maintenance_mode: '유지보수 모드',
      contact_info: '연락처 정보',
      security: '보안 및 알림',
      save_success: '설정이 성공적으로 저장되었습니다!'
    },
    contact: {
      title: '문의하기',
      desc: '무료 상담을 위해 정보를 남겨주세요',
      company_info: '회사 정보',
      form_title: '상담 요청 보내기',
      name: '성명',
      phone: '전화번호',
      email: '이메일',
      service: '관심 서비스',
      message: '메시지',
      submit: '요청 보내기',
      success: '성공적으로 전송되었습니다!'
    },
    about: {
      hero_badge: '10년 선구자',
      hero_title: 'CTC',
      hero_subtitle: '"재생 에너지로부터 지속 가능한 가치를 창출하고 고객의 번영하는 발전과 함께합니다."',
      ceo_title: 'Mr. Tran Thanh Xuan',
      ceo_role: '대표이사',
      milestone_1: 'CTC 설립',
      milestone_1_desc: '전기 산업에서 평판 좋은 브랜드의 탄생을 기념합니다.',
      milestone_2: '개발 전략',
      milestone_2_desc: '국가 에너지 개발 계획에 따라 적극적으로 실행합니다.',
      letter_title: 'CEO 편지',
      letter_greeting: '"CTC 전기 건설 및 컨설팅 주식회사(CTC)는 소중한 고객 여러분께 정중한 인사와 건강, 성공, 번영을 기원합니다!"',
      letter_p1: 'CTC 전기 건설 및 컨설팅 주식회사는 베트남 정부가 재생 에너지 개발을 우선시하던 2015년 11월 25일에 설립되었습니다.',
      letter_p2: 'CTC는 서비스, 기술 지원, EPC 계약자, 전력 유통업체 등 재생 에너지 산업에 필수적인 다양한 제품과 서비스를 제공합니다.',
      core_val_title: '핵심 가치',
      core_val_desc: '우리 회사의 평판은 우리가 구축한 신뢰와 포트폴리오를 기반으로 합니다.',
      vision_title: '비전 및 미션',
      vision_subtitle: '지속 가능한 개발 방향, 고객 중심.',
      mission: '미션',
      mission_desc: '최적의 기술 솔루션으로 고품질 제품을 제공하여 고객에게 절대적인 만족과 장기적인 경제적 이익을 창출합니다.',
      vision: '비전',
      vision_desc: '베트남의 재생 에너지 및 전기 건설 산업에서 신뢰의 선도적 상징이 되어 국가 Net Zero 목표와 함께합니다.',
      core_trust: '신뢰',
      core_quality: '품질',
      core_portfolio: '포트폴리오',
      areas_title: '사업 영역',
      area_epc: 'EPC 계약자',
      area_epc_desc: '옥상 및 지상 태양광 프로젝트를 위한 설계, 장비 공급 및 턴키 건설.',
      area_design: '컨설팅 및 설계',
      area_design_desc: '투자 프로젝트 계획, 기술 설계, 설계 검증 및 전기 건설 견적.',
      area_dist: '장비 유통',
      area_dist_desc: '태양광 패널(Canadian, Longi) 및 인버터(Huawei, SMA)의 공식 유통업체.',
      area_invest: '에너지 투자',
      area_invest_desc: '장기 에너지 프로젝트에 대한 계획 및 직접 투자.'
    },
    solutions: {
      hero_title: '에너지 솔루션',
      hero_subtitle: '종합 및 지속 가능',
      hero_desc: 'CTC의 가장 현대적인 태양광 모델로 비용을 최적화하고 환경을 보호하며 친환경 미래를 만듭니다.',
      category_title: '솔루션 카테고리',
      rooftop: '옥상 태양광',
      rooftop_desc: '공장, 사무실 또는 가정의 지붕 공간을 활용하여 전기를 생성합니다. 가장 효과적인 비용 절감 솔루션.',
      farm: '태양광 발전소',
      farm_desc: '국가 전력망에 연결된 대규모 프로젝트. 에너지 안보와 경제 발전에 크게 기여합니다.',
      floating: '수상 태양광',
      floating_desc: '수면(저수지, 수력 발전 댐)에 설치된 첨단 기술. 효율성을 높이고 토지 자원을 보존합니다.',
      cta_title: '어떤 솔루션이 적합한지 모르시겠습니까?',
      cta_desc: '우리 엔지니어링 팀이 실제 요구 사항에 따라 조사하고 무료 상담을 제공합니다.',
      cta_btn: '상담 받기',
      discover: '발견하기',
      other_services: '기타 서비스',
      smart_invest: '스마트 투자',
      invest_desc: '단 4-5년 만에 투자 회수. 다음 20년 동안 무료 혜택을 누리세요.',
      get_advice: '지금 조언 받기'
    },
    products: {
      filter: '필터',
      filter_tech: '기술 사양',
      power: '전력 (W)',
      efficiency: '효율 (%)',
      min: '최소',
      max: '최대',
      sort: '정렬',
      sort_default: '기본',
      sort_price_asc: '가격: 낮은 순',
      sort_price_desc: '가격: 높은 순',
      sort_name_asc: '이름: A-Z',
      category_list: '카테고리',
      tech_support: '기술 지원이 필요하십니까?',
      tech_support_desc: '우리 엔지니어링 팀이 적합한 장비를 선택하는 데 도움을 드립니다.',
      contact_now: '지금 연락하기',
      search_placeholder: '제품명, 코드 검색...',
      no_result: '제품을 찾을 수 없습니다',
      no_result_desc: '다른 키워드나 카테고리로 다시 시도하세요.',
      clear_filter: '필터 지우기',
      found: '검색 결과',
      products: '제품',
      eff_basic: '기본 < 90%',
      eff_good: '양호 90-95%',
      eff_high: '고효율 > 95%',
      eff_optimal: '최적 > 98%',
      detail_tab_desc: '설명',
      detail_tab_specs: '사양',
      detail_tab_reviews: '리뷰',
      call_to_buy: '구매 문의',
      add_to_quote: '견적에 추가',
      share: '이 제품 공유',
      warranty: '보증',
      authentic: '정품',
      payment: '결제',
      years: '년',
      write_review: '리뷰 작성',
      no_reviews: '이 제품에 대한 리뷰가 아직 없습니다.',
      be_first: '첫 번째로 경험을 공유하세요!',
      market_price: '시장 가격',
      contact_price: '가격 문의',
      reviews: '리뷰',
      views: '조회수',
      product_price: '제품 가격',
      like: '좋아요',
      share_btn: '공유',
      ai_analyzing: 'AI 분석 중...',
      ai_click: 'AI CTC 사용하기',
      ai_summary_desc: '기술 사양 요약',
      ai_summary: 'AI 요약',
      ai_comparing: 'AI 비교 중...',
      ai_compare_desc: '다른 제품과 비교',
      ai_compare: 'AI 비교',
      key_features: '주요 기능',
      tech_details: '기술 세부사항',
      related_products: '관련 제품'
    },
    projects: {
      title: '완료된 프로젝트',
      subtitle: '베트남 전역에서 친환경 에너지를 만드는 여정.',
      capacity: '용량',
      location: '위치',
      completion: '완료',
      type: '유형',
      status: '상태',
      view_detail: '상세보기',
      no_projects: '프로젝트를 찾을 수 없습니다.'
    },
    news: {
      title: '뉴스 및 이벤트',
      subtitle: '태양광 기술, 재생 에너지 동향 및 CTC 활동에 대한 최신 뉴스를 업데이트합니다.',
      no_news: '뉴스를 찾을 수 없습니다.'
    },
    resources: {
      title: '리소스 및 지원',
      subtitle: '카탈로그, 매뉴얼 및 보증 정책에 액세스하세요.',
      catalogue: '카탈로그',
      manual: '사용자 매뉴얼',
      policy: '보증 정책',
      download: '다운로드'
    },
    calculator: {
      title: '비용 계산기',
      bill_label: '월 평균 전기 요금',
      disclaimer: '*결과는 참고용입니다.',
      system_size: '권장 시스템',
      monthly_savings: '월 절감액',
      investment: '예상 투자',
      roi: 'ROI 기간',
      years: '년',
      consult_btn: '이 패키지에 대해 상담',
      intro_badge: '무료 도구',
      intro_title: '비용 견적 및 ROI',
      intro_desc: '태양광을 설치하고 싶지만 비용을 모르십니까? 빠른 계산기를 사용하여 전기 요금에 적합한 시스템의 개요를 확인하세요.',
      feature_1_title: '95% 정확도',
      feature_1_desc: '베트남의 실제 방사선 데이터를 기반으로 합니다.',
      feature_2_title: '시장 가격 업데이트',
      feature_2_desc: '장비 단가는 매주 업데이트됩니다.',
      usage_type: '전력 사용 유형',
      household: '가정용',
      household_desc: '생활용 전기',
      company: '기업용',
      company_desc: '사업용 전기',
      daytime_usage: '주간 전력 사용 비율',
      all_night: '전부 야간',
      all_day: '전부 주간',
      tip: '팁',
      tip_residential: '일반 가정은 주간에 20-40% 전력을 사용합니다 (요리, 세탁, 낮 시간 에어컨).',
      tip_commercial: '회사/사무실은 주간에 70-90% 전력을 사용합니다 (근무시간 8시-17시).',
      system_capacity: '권장 시스템 용량',
      storage: '저장 장치 (있는 경우)',
      estimated_bill: '예상 전기 요금',
      max_savings: '최대 절감액',
      recommended_area: '권장 설치 면적',
      per_month: '/월'
    },
    chat: {
      support: '온라인 지원',
      reply_time: '일반적으로 몇 분 안에 답변',
      welcome: 'CTC AI 어시스턴트가 인사드립니다. 오늘 어떻게 도와드릴까요?',
      placeholder: '메시지를 입력하세요...',
      typing: '입력 중...',
      send: '보내기'
    },
    login: {
      title: '관리자 로그인',
      email: '이메일',
      password: '비밀번호',
      btn: '로그인',
      error: '잘못된 이메일 또는 비밀번호',
      weak_password: '비밀번호는 최소 6자 이상이어야 합니다',
      back: '홈으로 돌아가기'
    }
  },
  // Japanese (日本語)
  ja: {
    nav: {
      home: 'ホーム',
      about: '会社概要',
      solutions: 'ソリューション',
      products: '製品',
      projects: 'プロジェクト',
      news: 'ニュース',
      resources: '資料',
      contact: 'お問い合わせ',
      'GIẢI PHÁP TOÀN DIỆN': '総合ソリューション',
      'HỆ THỐNG NĂNG LƯỢNG MẶT TRỜI TRÊN MÁI NHÀ': '屋上太陽光',
      'TRANG TRẠI NĂNG LƯỢNG MẶT TRỜI': '太陽光発電所',
      'HỆ THỐNG NĂNG LƯỢNG MẶT TRỜI NỔI': '水上太陽光',
      'TẤM PIN NĂNG LƯỢNG MẶT TRỜI': '太陽光パネル',
      'BỘ HÒA LƯỚI (INVERTER)': 'インバーター',
      'HỆ THỐNG LƯU TRỮ ĐIỆN': 'エネルギー貯蔵システム',
      'PHỤ KIỆN LẮP ĐẶT': '設置付属品'
    },
    header: {
      slogan: 'ベトナム最高の太陽エネルギーソリューション',
      admin: '管理者',
      hotline: 'ホットライン'
    },
    footer: {
      about_title: '会社概要',
      quick_links: 'クイックリンク',
      solutions_title: 'ソリューション',
      contact_title: '連絡先',
      desc: 'CTC電気建設コンサルティング株式会社（CTC）。再生可能エネルギー分野のパイオニア。',
      address: '259 The Lu, Son Tra, Da Nang',
      copyright: '© 2026 CTC. 全著作権所有。'
    },
    common: {
      loading: '読み込み中...',
      search: '検索...',
      light: 'ライト',
      dark: 'ダーク',
      theme_light: 'ライトモード',
      theme_dark: 'ダークモード',
      theme_auto: 'システム設定',
      view_details: '詳細',
      add_to_cart: 'カートに追加',
      buy_now: '今すぐ購入',
      close: '閉じる',
      cancel: 'キャンセル',
      save: '保存',
      delete: '削除',
      edit: '編集',
      add: '追加',
      action: 'アクション',
      image: '画像',
      name: '名前',
      category: 'カテゴリー',
      price: '価格',
      stock: '在庫',
      description: '説明',
      status: 'ステータス',
      in_stock: '在庫あり',
      out_of_stock: '在庫切れ',
      all_categories: 'すべてのカテゴリー',
      all: 'すべて'
    },
    home: {
      hero_badge: '最新AIインバーター技術32',
      hero_title: 'クリーンエネルギー',
      hero_subtitle: '持続可能な投資',
      hero_desc: 'CTCは包括的な太陽光発電ソリューションを提供し、電気代を節約し、グリーンな未来を創造します。',
      get_quote: '見積もりを取得',
      view_projects: 'プロジェクトを見る',
      why_choose: '選ばれる理由',
      why_choose_title: '国際基準のエネルギーソリューション',
      why_choose_desc: '私たちは単に機器を設置するだけでなく、持続可能な金融投資ソリューションと絶対的な安全性を提供します。',
      latest_products: '最新製品',
      latest_products_desc: '耐久性と効率性を保証するため、世界トップ5の機器（Tier 1）のみを流通しています。',
      view_all_products: 'すべて見る',
      projects_badge: 'プロジェクト',
      featured_projects: '注目プロジェクト',
      featured_projects_sub: 'CTCの品質を証明するプロジェクト。',
      testimonials: 'お客様の声',
      testimonials_title: 'お客様の声をお聞きください',
      news_events: 'ニュース＆イベント',
      news_badge: 'ニュース',
      read_more: '続きを読む',
      cta_badge: '今すぐ始める',
      cta_title_1: '切り替え準備は',
      cta_title_2: 'できていますか？',
      call_now: '今すぐ電話',
      free_consult: '無料相談',
      warranty_25: '25年保証',
      save_70: '70%エネルギー節約',
      ready_to_switch: 'グリーンエネルギーへの切り替え準備はできましたか？',
      ready_desc: '今日CTCに連絡して、無料調査とコンサルティングを受けてください。電気代を即座に70％節約できます。',
      contact_consult: 'お問い合わせ',
      partners_title: '主要技術パートナー',
      partners_supplier: 'サプライヤーパートナー',
      partners_financial: '金融パートナー',
      stat_assets: '総資産',
      stat_partners: '戦略的パートナー',
      stat_capacity: '総容量',
      stat_satisfaction: '主要技術者',
      workflow_badge: 'プロセス',
      workflow_title: '標準実装プロセス',
      step_1: '調査＆コンサルティング',
      step_1_desc: '屋根の状態と電力需要を評価します。',
      step_2: '技術設計',
      step_2_desc: '詳細図面と発電量シミュレーション。',
      step_3: '設置',
      step_3_desc: '迅速、安全、標準的な設置。',
      step_4: '保証＆メンテナンス',
      step_4_desc: '24時間365日の監視と定期メンテナンス。',
      why_1_title: '最大パフォーマンス',
      why_1_desc: '最適設計とTier 1機器により、80％以上のシステムパフォーマンスを保証します。',
      why_2_title: '25年保証',
      why_2_desc: '12年間のパネル1対1交換ポリシー、25年間のパフォーマンス保証。',
      why_3_title: '専門エンジニアリング',
      why_3_desc: 'よく訓練され、認定された実務経験のあるエンジニア。',
      why_4_title: 'スマートストレージ',
      why_4_desc: 'ハイブリッド/ESSシステムで24時間365日電力を自給自足、停電の心配なし。',
      why_5_title: '信頼できるブランド',
      why_5_desc: 'ベトナム市場でのHuawei、Canadian Solar、Longiの戦略的パートナー。',
      why_6_title: 'グリーンコミットメント',
      why_6_desc: '各設置システムは、数百本の木を植えるのと同等のトンのCO2を削減します。',
      support_badge: 'サポート',
      faq_title: 'よくある質問',
      faq_desc: '太陽エネルギーに関する一般的な質問に答えます。',
      need_help: 'さらにサポートが必要ですか？',
      contact_advisor: 'アドバイザーに連絡',
      faq_1_q: '停電時に太陽光システムは動作しますか？',
      faq_1_a: '標準的な系統連系システムの場合、安全のため停電時にインバーターが遮断されます。ただし、ハイブリッドシステム（ストレージ付き）を使用すると、重要な負荷に対する電力がまだあります。',
      faq_2_q: '太陽光パネルの寿命はどのくらいですか？',
      faq_2_a: '現在のTier 1太陽光パネルの設計寿命は最大30〜35年です。CTCは25年間80％以上のパフォーマンスを保証します。',
      faq_3_q: 'メンテナンスコストは高いですか？',
      faq_3_a: '太陽光システムは耐久性があります。メンテナンスは主に定期的な清掃（3〜6か月ごと）であり、コストは非常に低いです。',
      faq_4_q: '設置時間はどのくらいかかりますか？',
      faq_4_a: '家庭用（3kW〜10kW）の場合、設置は1〜2日かかります。産業プロジェクトは規模によって異なり、通常2〜4週間かかります。',
      about_badge: '会社概要',
      about_title: 'CTC - 信頼できるパートナー',
      about_desc: 'CTC電気コンサルティング建設株式会社（CTC）は2015年に設立され、経験豊富なエンジニアと先進技術で包括的な再生可能エネルギーソリューションを専門としています。',
      about_desc_2: '私たちはHuawei、Canadian Solar、Longiなどの世界有数のブランドの戦略的パートナーとして、お客様に最も競争力のある価格で高品質の製品を提供しています。',
      mission: 'ミッション',
      mission_desc: 'すべての家庭にクリーンエネルギーを提供',
      vision: 'ビジョン',
      vision_desc: '再生可能エネルギー市場をリード',
      values: '価値',
      values_desc: '信頼 - 品質 - 持続可能性',
      learn_more: '詳細を見る',
      contact_us: '今すぐお問い合わせ',
      team_badge: 'プロフェッショナルチーム',
      team_title: '専門家チームに会う',
      team_desc: 'お客様に最高のソリューションを提供することに専念する経験豊富なエンジニアと専門家。',
      team_ceo: '最高経営責任者',
      team_cto: '最高技術責任者',
      team_engineer: 'チーフエンジニア',
      team_manager: 'プロジェクトマネージャー',
      join_team: '私たちのチームに参加',
      join_team_title: '一緒に創造',
      join_team_highlight: 'グリーンな未来',
      opportunity: '機会',
      join_team_desc: '私たちは一緒に発展し、グリーンエネルギーの未来を創造する優秀な人材を常に探しています。',
      apply_now: '今すぐ応募'
    },
    admin: {
      dashboard: 'ダッシュボード',
      users: 'アカウント管理',
      content: 'コンテンツ管理',
      products: '製品',
      projects: 'プロジェクト',
      news: 'ニュース',
      testimonials: '顧客',
      partners: 'パートナー',
      settings: '設定',
      categories: 'カテゴリー管理',
      reviews: '顧客レビュー',
      goals: '目標管理',
      contacts: '連絡先管理',
      team: 'スタッフ管理',
      project_categories: 'プロジェクトカテゴリー',
      news_categories: 'ニュースカテゴリー',
      logout: 'ログアウト',
      welcome: 'ようこそ',
      search_placeholder: '管理者で検索...',
      manage_content: 'コンテンツ管理',
      settings_title: 'システム設定',
      general_info: '一般情報',
      site_name: 'ウェブサイト名',
      maintenance_mode: 'メンテナンスモード',
      contact_info: '連絡先情報',
      security: 'セキュリティ＆通知',
      save_success: '設定が正常に保存されました！'
    },
    contact: {
      title: 'お問い合わせ',
      desc: '無料相談のために情報を残してください',
      company_info: '会社情報',
      form_title: '相談リクエストを送信',
      name: '氏名',
      phone: '電話番号',
      email: 'メール',
      service: '関心のあるサービス',
      message: 'メッセージ',
      submit: 'リクエストを送信',
      success: '正常に送信されました！'
    },
    about: {
      hero_badge: '10年のパイオニア',
      hero_title: 'CTC',
      hero_subtitle: '「再生可能エネルギーから持続可能な価値を創造し、お客様の繁栄する発展とともに歩みます。」',
      ceo_title: 'Mr. Tran Thanh Xuan',
      ceo_role: '代表取締役',
      milestone_1: 'CTC設立',
      milestone_1_desc: '電気業界で評判の良いブランドの誕生を記念します。',
      milestone_2: '開発戦略',
      milestone_2_desc: '国家エネルギー開発計画に従って積極的に実行します。',
      letter_title: 'CEOメッセージ',
      letter_greeting: '「CTC電気建設コンサルティング株式会社（CTC）は、大切なお客様に敬意を表し、健康、成功、繁栄を祈ります！」',
      letter_p1: 'CTC電気建設コンサルティング株式会社は、ベトナム政府が再生可能エネルギー開発を優先していた2015年11月25日に設立されました。',
      letter_p2: 'CTCは、サービス、技術サポート、EPCコントラクター、電力流通業者など、再生可能エネルギー産業に不可欠なさまざまな製品とサービスを提供しています。',
      core_val_title: 'コアバリュー',
      core_val_desc: '当社の評判は、私たちが構築した信頼とポートフォリオに基づいています。',
      vision_title: 'ビジョン＆ミッション',
      vision_subtitle: '持続可能な開発方向、顧客中心。',
      mission: 'ミッション',
      mission_desc: '最適な技術ソリューションで高品質の製品を提供し、お客様に絶対的な満足と長期的な経済的利益を創出します。',
      vision: 'ビジョン',
      vision_desc: 'ベトナムの再生可能エネルギーおよび電気建設業界で信頼のリーディングシンボルとなり、国家ネットゼロ目標とともに歩みます。',
      core_trust: '信頼',
      core_quality: '品質',
      core_portfolio: 'ポートフォリオ',
      areas_title: '事業分野',
      area_epc: 'EPCコントラクター',
      area_epc_desc: '屋上および地上太陽光プロジェクトの設計、機器供給、ターンキー建設。',
      area_design: 'コンサルティング＆設計',
      area_design_desc: '投資プロジェクト計画、技術設計、設計検証、電気建設見積もり。',
      area_dist: '機器流通',
      area_dist_desc: '太陽光パネル（Canadian、Longi）およびインバーター（Huawei、SMA）の正規販売代理店。',
      area_invest: 'エネルギー投資',
      area_invest_desc: '長期エネルギープロジェクトの計画と直接投資。'
    },
    solutions: {
      hero_title: 'エネルギーソリューション',
      hero_subtitle: '包括的＆持続可能',
      hero_desc: 'CTCの最も現代的な太陽光モデルでコストを最適化し、環境を保護し、グリーンな未来を創造します。',
      category_title: 'ソリューションカテゴリー',
      rooftop: '屋上太陽光',
      rooftop_desc: '工場、オフィス、または家庭の屋根スペースを活用して電気を生成します。最も効果的なコスト削減ソリューション。',
      farm: '太陽光発電所',
      farm_desc: '国家電力網に接続された大規模プロジェクト。エネルギー安全保障と経済発展に大きく貢献します。',
      floating: '水上太陽光',
      floating_desc: '水面（貯水池、水力発電ダム）に設置された先進技術。効率を高め、土地資源を保全します。',
      cta_title: 'どのソリューションが適しているかわかりませんか？',
      cta_desc: '当社のエンジニアリングチームが実際のニーズに基づいて調査し、無料相談を提供します。',
      cta_btn: '相談を受ける',
      discover: '発見する',
      other_services: 'その他のサービス',
      smart_invest: 'スマート投資',
      invest_desc: 'わずか4〜5年で投資回収。次の20年間無料の利益を享受できます。',
      get_advice: '今すぐアドバイスを受ける'
    },
    products: {
      filter: 'フィルター',
      filter_tech: '技術仕様',
      power: '電力（W）',
      efficiency: '効率（％）',
      min: '最小',
      max: '最大',
      sort: '並べ替え',
      sort_default: 'デフォルト',
      sort_price_asc: '価格：低い順',
      sort_price_desc: '価格：高い順',
      sort_name_asc: '名前：A-Z',
      category_list: 'カテゴリー',
      tech_support: '技術サポートが必要ですか？',
      tech_support_desc: '当社のエンジニアリングチームが適切な機器の選択をお手伝いします。',
      contact_now: '今すぐお問い合わせ',
      search_placeholder: '製品名、コードを検索...',
      no_result: '製品が見つかりません',
      no_result_desc: '別のキーワードまたはカテゴリーで再試行してください。',
      clear_filter: 'フィルターをクリア',
      found: '検索結果',
      products: '製品',
      eff_basic: '基本 < 90%',
      eff_good: '良好 90-95%',
      eff_high: '高効率 > 95%',
      eff_optimal: '最適 > 98%',
      detail_tab_desc: '説明',
      detail_tab_specs: '仕様',
      detail_tab_reviews: 'レビュー',
      call_to_buy: '購入のお問い合わせ',
      add_to_quote: '見積もりに追加',
      share: 'この製品を共有',
      warranty: '保証',
      authentic: '正規品',
      payment: '支払い',
      years: '年',
      write_review: 'レビューを書く',
      no_reviews: 'この製品のレビューはまだありません。',
      be_first: '最初に体験を共有してください！',
      market_price: '市場価格',
      contact_price: 'お問い合わせ',
      reviews: 'レビュー',
      views: '閲覧数',
      product_price: '製品価格',
      like: 'いいね',
      share_btn: '共有',
      ai_analyzing: 'AI分析中...',
      ai_click: 'AI CTCを使用',
      ai_summary_desc: '仕様の要約',
      ai_summary: 'AI要約',
      ai_comparing: 'AI比較中...',
      ai_compare_desc: '他の製品と比較',
      ai_compare: 'AI比較',
      key_features: '主な機能',
      tech_details: '技術詳細',
      related_products: '関連製品'
    },
    projects: {
      title: '完了プロジェクト',
      subtitle: 'ベトナム全土でグリーンエネルギーを創造する旅。',
      capacity: '容量',
      location: '場所',
      completion: '完了',
      type: 'タイプ',
      status: 'ステータス',
      view_detail: '詳細を見る',
      no_projects: 'プロジェクトが見つかりません。'
    },
    news: {
      title: 'ニュース＆イベント',
      subtitle: '太陽光技術、再生可能エネルギーのトレンド、CTCの活動に関する最新ニュースを更新します。',
      no_news: 'ニュースが見つかりません。'
    },
    resources: {
      title: 'リソース＆サポート',
      subtitle: 'カタログ、マニュアル、保証ポリシーにアクセスします。',
      catalogue: 'カタログ',
      manual: 'ユーザーマニュアル',
      policy: '保証ポリシー',
      download: 'ダウンロード'
    },
    calculator: {
      title: 'コスト計算機',
      bill_label: '月平均電気料金',
      disclaimer: '*結果は参考用です。',
      system_size: '推奨システム',
      monthly_savings: '月間節約額',
      investment: '推定投資',
      roi: 'ROI期間',
      years: '年',
      consult_btn: 'このパッケージについて相談',
      intro_badge: '無料ツール',
      intro_title: 'コスト見積もり＆ROI',
      intro_desc: '太陽光を設置したいがコストがわかりませんか？クイック計算機を使用して、電気料金に適したシステムの概要を確認してください。',
      feature_1_title: '95％の精度',
      feature_1_desc: 'ベトナムの実際の放射線データに基づいています。',
      feature_2_title: '市場価格更新',
      feature_2_desc: '機器単価は毎週更新されます。',
      usage_type: '電力使用タイプ',
      household: '家庭用',
      household_desc: '生活用電力',
      company: '企業用',
      company_desc: '事業用電力',
      daytime_usage: '日中電力使用率',
      all_night: '全て夜間',
      all_day: '全て日中',
      tip: 'ヒント',
      tip_residential: '一般家庭は日中に20-40%の電力を使用します（調理、洗濯、昼間のエアコン）。',
      tip_commercial: '企業/オフィスは日中に70-90%の電力を使用します（勤務時間8時-17時）。',
      system_capacity: '推奨システム容量',
      storage: '蓄電池（ある場合）',
      estimated_bill: '予想電気料金',
      max_savings: '最大節約額',
      recommended_area: '推奨設置面積',
      per_month: '/月'
    },
    chat: {
      support: 'オンラインサポート',
      reply_time: '通常数分で返信',
      welcome: 'CTC AIアシスタントがご挨拶します。今日はどのようにお手伝いできますか？',
      placeholder: 'メッセージを入力...',
      typing: '入力中...',
      send: '送信'
    },
    login: {
      title: '管理者ログイン',
      email: 'メール',
      password: 'パスワード',
      btn: 'ログイン',
      error: '無効なメールまたはパスワード',
      weak_password: 'パスワードは少なくとも6文字である必要があります',
      back: 'ホームに戻る'
    }
  },
  zh: { 
      nav: { home: '首页', about: '关于我们', solutions: '解决方案', products: '产品中心', projects: '项目案例', news: '新闻资讯', resources: '资料下载', contact: '联系我们' }, 
      common: { loading: '加载中...', light: '浅色', dark: '深色', theme_light: '浅色模式', theme_dark: '深色模式', theme_auto: '跟随系统' },
      home: { 
        hero_title: '清洁能源', hero_subtitle: '可持续投资', hero_desc: 'CTC 提供全面的太阳能解决方案。', get_quote: '获取报价',
        workflow_badge: '流程', workflow_title: '标准实施流程',
        projects_badge: '项目', featured_projects: '精选项目', featured_projects_sub: '证明CTC品质的项目。',
        testimonials: '客户评价', testimonials_title: '客户怎么说',
        news_events: '新闻资讯', news_badge: '新闻', read_more: '阅读更多',
        cta_badge: '立即开始', cta_title_1: '准备转换', cta_title_2: '到绿色能源？',
        call_now: '立即致电', free_consult: '免费咨询', warranty_25: '25年保修', save_70: '节省70%电费',
        support_badge: '支持', faq_title: '常见问题', faq_desc: '解答关于太阳能的常见问题。',
        need_help: '需要更多帮助？', contact_advisor: '联系顾问',
        join_team: '加入我们', join_team_title: '共同创造', join_team_highlight: '绿色未来', opportunity: '机会',
        join_team_desc: '我们一直在寻找对清洁能源充满热情的人才。', apply_now: '立即申请'
      },
      about: { letter_title: '致辞', vision: '愿景', mission: '使命' },
      calculator: {
        title: '成本计算器', bill_label: '月平均电费', disclaimer: '*结果仅供参考。',
        system_size: '推荐系统', monthly_savings: '月节省', investment: '预计投资',
        roi: 'ROI期间', years: '年', consult_btn: '咨询此套餐',
        usage_type: '用电类型', household: '家庭用户', household_desc: '生活用电',
        company: '企业用户', company_desc: '商业用电', daytime_usage: '白天用电比例',
        all_night: '全部夜间', all_day: '全部白天', tip: '提示',
        tip_residential: '一般家庭白天用电占20-40%（做饭、洗衣、午间空调）。',
        tip_commercial: '公司/办公室白天用电占70-90%（工作时间8点-17点）。',
        system_capacity: '推荐系统容量', storage: '储能（如有）', estimated_bill: '预计电费',
        max_savings: '最大节省', recommended_area: '推荐安装面积', per_month: '/月'
      }
  },
  de: { 
      nav: { home: 'Startseite', about: 'Über uns', solutions: 'Lösungen', products: 'Produkte', projects: 'Projekte', news: 'Nachrichten', resources: 'Ressourcen', contact: 'Kontakt' }, 
      common: { loading: 'Laden...', light: 'Hell', dark: 'Dunkel', theme_light: 'Heller Modus', theme_dark: 'Dunkler Modus', theme_auto: 'Systemeinstellung' },
      home: { 
        hero_title: 'Saubere Energie', hero_subtitle: 'Nachhaltige Investition', hero_desc: 'CTC bietet umfassende Solarlösungen.', get_quote: 'Angebot anfordern',
        workflow_badge: 'Prozess', workflow_title: 'Standard-Implementierungsprozess',
        projects_badge: 'Projekte', featured_projects: 'Ausgewählte Projekte', featured_projects_sub: 'Projekte, die die Qualität von CTC bestätigen.',
        testimonials: 'Kundenbewertungen', testimonials_title: 'Was unsere Kunden sagen',
        news_events: 'Nachrichten & Events', news_badge: 'Nachrichten', read_more: 'Weiterlesen',
        cta_badge: 'Jetzt starten', cta_title_1: 'Bereit zum Wechsel', cta_title_2: 'zu grüner Energie?',
        call_now: 'Jetzt anrufen', free_consult: 'Kostenlose Beratung', warranty_25: '25 Jahre Garantie', save_70: '70% Energie sparen',
        support_badge: 'Support', faq_title: 'Häufige Fragen', faq_desc: 'Antworten auf häufige Fragen zu Solarenergie.',
        need_help: 'Brauchen Sie mehr Hilfe?', contact_advisor: 'Berater kontaktieren',
        join_team: 'Werden Sie Teil', join_team_title: 'Gemeinsam gestalten', join_team_highlight: 'Grüne Zukunft', opportunity: 'Chance',
        join_team_desc: 'Wir suchen immer talentierte Menschen mit Leidenschaft für saubere Energie.', apply_now: 'Jetzt bewerben'
      },
      about: { letter_title: 'CEO Brief', vision: 'Vision', mission: 'Mission' },
      calculator: {
        title: 'Kostenrechner', bill_label: 'Monatliche Stromrechnung', disclaimer: '*Ergebnisse dienen nur als Referenz.',
        system_size: 'Empfohlenes System', monthly_savings: 'Monatliche Einsparungen', investment: 'Geschätzte Investition',
        roi: 'ROI-Zeitraum', years: 'Jahre', consult_btn: 'Beratung zu diesem Paket',
        usage_type: 'Stromverbrauchstyp', household: 'Haushalt', household_desc: 'Privater Stromverbrauch',
        company: 'Unternehmen', company_desc: 'Gewerblicher Stromverbrauch', daytime_usage: 'Tagesverbrauchsanteil',
        all_night: 'Alles nachts', all_day: 'Alles tagsüber', tip: 'Tipp',
        tip_residential: 'Typische Haushalte verbrauchen 20-40% des Stroms tagsüber (Kochen, Wäsche, Nachmittags-AC).',
        tip_commercial: 'Unternehmen/Büros verbrauchen 70-90% des Stroms tagsüber (Arbeitszeit 8-17 Uhr).',
        system_capacity: 'Empfohlene Systemkapazität', storage: 'Speicher (falls vorhanden)', estimated_bill: 'Geschätzte Stromrechnung',
        max_savings: 'Maximale Einsparungen', recommended_area: 'Empfohlene Fläche', per_month: '/Monat'
      }
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isLoading: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation cache để tránh lookup nhiều lần
const translationCache = new Map<string, string>();

// Helper function để get nested value
function getNestedValue(obj: any, keys: string[]): any {
  return keys.reduce((current, key) => current?.[key], obj);
}

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  // Load language from localStorage hoặc default 'vi'
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('app_language');
      if (saved && ['vi', 'en', 'ko', 'ja', 'zh', 'de'].includes(saved)) {
        return saved as Language;
      }
    }
    return 'vi';
  });
  
  const [isLoading, setIsLoading] = useState(false);

  // Persist language to localStorage
  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('app_language', language);
    }
  }, [language]);

  // Optimized setLanguage with loading state and page reload
  const setLanguage = useCallback((lang: Language) => {
    if (lang === language) return; // Skip if same language
    
    setIsLoading(true);
    // Clear cache khi đổi ngôn ngữ
    translationCache.clear();
    // Save to localStorage first
    localStorage.setItem('app_language', lang);
    // Reload page to fetch data with new language
    window.location.reload();
  }, [language]);

  // Memoized translation function với caching
  const t = useCallback((path: string): string => {
    // Check cache trước
    const cacheKey = `${language}:${path}`;
    const cached = translationCache.get(cacheKey);
    if (cached) return cached;

    const keys = path.split('.');
    
    // Try current language
    let value = getNestedValue(translations[language], keys);
    
    if (value && typeof value === 'string') {
      translationCache.set(cacheKey, value);
      return value;
    }

    // Fallback mechanism
    if (language !== 'vi') {
      // Try Vietnamese
      value = getNestedValue(translations['vi'], keys);
      if (value && typeof value === 'string') {
        translationCache.set(cacheKey, value);
        return value;
      }
    }
    
    if (language !== 'en') {
      // Try English
      value = getNestedValue(translations['en'], keys);
      if (value && typeof value === 'string') {
        translationCache.set(cacheKey, value);
        return value;
      }
    }

    // Return last key as fallback
    const fallback = keys[keys.length - 1] || path;
    translationCache.set(cacheKey, fallback);
    return fallback;
  }, [language]);

  // Memoize context value để tránh re-render không cần thiết
  const contextValue = useMemo(
    () => ({ language, setLanguage, t, isLoading }),
    [language, setLanguage, t, isLoading]
  );

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
